name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - docker/*
      - scripts/*
  
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      docker/*
      scripts/*
  
  workflow_dispatch:

env:
  GH_REPO_PATH: ghcr.io/overlydev/oracle-nabber
  DOCKER_REPO_PATH: overlydev/oracle-nabber

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ GH_REPO_PATH }}
            ${{ DOCKER_REPO_PATH }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up build context
        run: |
          mkdir -p docker/_context
          cp scripts/*.sh docker/_context/.
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          context: docker/_context
          
